- id: actionlint
  name: Lint GitHub Actions workflow files
  description: Runs actionlint to lint GitHub Actions workflow files
  language: system
  types: ["yaml"]
  files: "^.github/workflows/"
  entry: actionlint
